src/cs/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from ziff.views import book, motivation, pre, note
urlpatterns = [
	path('', book),
	path('motivation/',motivation),
	path('previous/', pre),
	path('notes/', note),
]

src/ziff/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


from .views import home,req,gate
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 

urlpatterns = [
    path('', home),
    path('request/',req),
    path('gate/',gate),
    path('boss/', admin.site.urls),
    path('materials/',include('cs.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cs/models.py
from django.db import models

'''choice = [
('cs','CSE/IT'),
('me','ME'),
('ece','ECE'),
('ee','EE'),
('o','Others'),
]'''

# Create your models here.
class Post(models.Model):
	Subject = models.CharField(max_length=5)

src/ziff/forms.py
from django import forms

from cs.models import Post

choice = [
('cs','CSE/IT'),
('mech','ME'),
('ece','ECE'),
('ee','EE'),
('o','Other'),
]

class RequestForm(forms.Form):
	Subject = forms.ChoiceField(required=True, label='Choose your stream ',widget=forms.RadioSelect, choices=choice)
	#add uncommented fields in Meta class and model 
	
	#class Meta:
		#model = Post
		#fields = ['Subject',
		#	]

src/cs/views.py
from django.shortcuts import render

# Create your views here.

src/ziff/views.py
from django.http import HttpResponse
from django.shortcuts import render


from .forms import RequestForm
from cs.models import Post

def home(Request):
	return render(Request, 'index.html', {'title': 'E-Library : A Study Platform'})

def req(Request):
	#sub = Request.POST['username']
	sub="null"
	form = RequestForm(Request.POST or None)
	if form.is_valid():
		sub = form.cleaned_data['Subject']
	print(sub)
	return render(Request, 'request.html',{'Subject' : sub, 'form' : form})

def gate(Request):
	#form.cleaned_data.get('Subject')
	#qr = RequestForm()
	#sub = qr.Subject
	sub="cs"
	sub = Request.POST['Subject']
	print(sub)
	if sub == 'cs':
		bg = 'https://c0.wallpaperflare.com/preview/187/633/72/5be997aec83a2.jpg'	
		context = {'title':'GATE', 'sub':'Computer Science and Information Technology', 'bg': bg}
	return render(Request, 'gate/content.html', context)	

def book(request):
	return render(request, 'gate/materials/book.html')

def motivation(request):
	return render(request, 'gate/materials/motivation.html')

def note(request):
	return render(request, 'gate/materials/notes.html')

def pre(request):
	return render(request, 'gate/materials/previous.html')

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="/static/base.css"/>

  </head>
  <body>
    
    <div>
      <div class="main" style="color: #D9F6EB;">
        <div class="w3-jumbo container" style="background-color:#265F4A " style="width: 100%">
          <div >
            <img src="https://freesvg.org/img/1545520056.png" alt="Prof. Owl" height="150" width="150" align = "right" class="responsive" >
           </div>
           <a class="main" href=""><u><strong >E-library</strong></u></a><p></p><p></p>
        <div style="position: absolute" style="top: 200px">{% block content %} tjis{% endblock %}</div>
        </div>
      </div>
    </div>
  
    
  
  </body>
</html>

src/templates/gate/baseFrame.html
<!DOCTYPE html>
<html>
<head>
  <title>Books&Notes</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/static/baseFrame.css">
  <script src="https://kit.fontawesome.com/8a9412ad16.js"></script>
   
<script>
function openNav() {
  document.getElementById("myNav").style.width = "100%";
}

function closeNav() {
  document.getElementById("myNav").style.width = "0%";
}
</script>
</head>
<body>
<section id="Nav"> 
   <div id="myNav" class="overlay">
  	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  	<div class="overlay-content">
    	<a href="#MainPage" onclick="closeNav()"></i>MainPage</a>
    	<a href="#"></i>Gate- books & notes</a>
    	<a href="#"></i>Gate- videos</a>
    	<a href="#"></i>Gate- Preparation<sup>online resource</sup></a>
    		<a href="https://chat.whatsapp.com/HM9VJz4a8Ce0TvUZingcxF" target="_blank" class="whataap" title="Join to our whataap group----->>">--need any book??</a>
    </div>
   </div>
 <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;Menu</span>
</body>
</html>

src/templates/gate/books_notes/Pre/previous.html
<!DOCTYPE html>
<html>
<head>
  <title>QUESTION-PAPER</title>
  <link rel="icon" type="image/ico" href="capture.png" />
<meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="icon" type="image/ico" href="title.png" />
  <link rel="stylesheet" href="books.css">
  <script src="https://kit.fontawesome.com/8a9412ad16.js"></script>
 <script>
function openNav() {
  document.getElementById("myNav").style.width = "100%";
}

function closeNav() {
  document.getElementById("myNav").style.width = "0%";
}
</script>
</head>
<body>
<section id="Nav">
   <div id="myNav" class="overlay">
  	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  	<div class="overlay-content">
    	<a href="../../index.html" onclick="closeNav()"></i>MainPage</a>
    	<a href="../book/book.html"></i>Gate- books & notes</a>
    	<a href="#"></i>Gate- videos</a>
    	<a href="#"></i>Gate- Preparation<sup>online resource</sup></a>
    		<a href="https://chat.whatsapp.com/HM9VJz4a8Ce0TvUZingcxF" target="_blank" class="whataap" title="Join to our whataap group----->>">--need any book??</a>
    </div>
   </div>
   <div>
 <span style="font-size:30px;cursor:pointer" class="Menu" onclick="openNav()">&#9776;</span>
 <img class="logo" id="logo" src="image.jpg">
</div>
			</section>
			<section id="navbar">
			<div class="topnav">
  <a  href="../book/book.html">BOOK SUGGESTION</a>
  <a  href="../notes/notes.html">NOTES</a>
  <a class="active" href="" >QUESTION PAPER<h6 style="margin-top:-5px;text-align: right;font-size: 10px; margin-bottom:-6px;">Previous year</h6></a>
  <a href="../motivation/motivation.html">MOTIVATION</a>
</div>
			</section>
      <!------ main -------->
      <section class="table1">
        <h4>Previous years GATE CSE and IT Papers Download Link</h4>
        <img class="img" src="img.jpg">
        <div class="table">
          <table>
            <tr class="sub">
              <td>Year</td>
              <td>Original Paper</td>
              <td>Official Keys</td>
            </tr>
            <tr>
              <td>2019</td>
              <td><a class="link" href="">2019 Paper</a></td>
              <td><a class="link" href="">2019 Keys</a></td>
            </tr>
            <tr>
              <td>2018</td>
              <td><a class="link" href="">2018 Paper</a></td>
              <td><a class="link" href="">2018 keys</a></td>
            </tr>
            <tr>
              <td>2017</td>
              <td><a class="link" href="">2017 Paper</a></td>
              <td><a class="link" href="">2017 Keys</a></td>
            </tr>
            <tr>
              <td>2016</td>
              <td><a class="link" href="">2016 Paper</a></td>
              <td><a class="link" href="">2016 Keys</a></td>
            </tr>
            <tr>
              <td>2015</td>
              <td><a class="link" href="">2015 Paper</a></td>
              <td><a class="link" href="">2015 Keys</a></td>
            </tr>
            <tr>
              <td>2014</td>
              <td><a class="link" href="">2014 Paper</a></td>
              <td><a class="link" href="">2014 Keys</a></td>
            </tr>
            <tr>
              <td>2013</td>
              <td><a class="link" href="">2013 Paper</a></td>
              <td><a class="link" href="">2013 Keys</a></td>
            </tr>
            <tr>
              <td>2012</td>
              <td><a class="link" href="">2012 Paper</a></td>
              <td><a class="link" href="">2012 Keys</a></td>
            </tr>
            <tr>
              <td>2011</td>
              <td><a class="link" href="">2011 Paper</a></td>
              <td><a class="link" href="">2011 Keys</a></td>
            </tr>
            <tr>
              <td>2010</td>
              <td><a class="link" href="">2010 Paper</a></td>
              <td><a class="link" href="">2010 Keys</a></td>
            </tr>
            <tr>
              <td>2009</td>
              <td><a class="link" href="">2009 Paper</a></td>
              <td><a class="link" href="">2009 Keys</a></td>
            </tr>
            <tr>
              <td>2008</td>
              <td><a class="link" href="">2008 Paper</a></td>
              <td><a class="link" href="">2008 Keys</a></td>
            </tr>
            <tr>
              <td>2007</td>
              <td><a class="link" href="">2007 Paper</a></td>
              <td><a class="link" href="">2007 Keys</a></td>
            </tr>
            <tr>
              <td>2006</td>
              <td><a class="link" href="">2006 Paper</a></td>
              <td><a class="link" href="">2006 Keys</a></td>
            </tr>
            <tr>
              <td>2005</td>
              <td><a class="link" href="">2005 Paper</a></td>
              <td><a class="link" href="">2005 Keys</a></td>
            </tr>
            <tr>
              <td>2004</td>
              <td><a class="link" href="">2004 Paper</a></td>
              <td><a class="link" href=""> 2004 Keys</a></td>
            </tr>
            <tr>
              <td>2003</td>
              <td><a class="link" href="">2003 Paper</a></td>
              <td><a class="link" href="">2003 Keys</a></td>
            </tr>
            <tr>
              <td>2002</td>
              <td><a class="link" href="">2002 Paper</a></td>
              <td><a class="link" href="">2002 Keys</a></td>
            </tr>
            <tr>
              <td>2001</td>
              <td><a class="link" href="">2001 Paper</a></td>
              <td><a class="link" href="">2001 Keys</a></td>
            </tr>
            <tr>
              <td>2000</td>
              <td><a class="link" href="">2000 Paper</a></td>
              <td><a class="link" href="">2000 Keys</a></td>
            </tr>
            <tr>
              <td>1999</td>
              <td><a class="link" href="">1999 Paper</a></td>
              <td><a class="link" href="">1999 Keys</a></td>
            </tr>
            <tr>
              <td>1998</td>
              <td><a class="link" href="">1998 Paper</a></td>
              <td><a class="link" href="">1998 Keys</a></td>
            </tr>
            <tr>
              <td>1997</td>
              <td><a class="link" href="">1997 Paper</a></td>
              <td><a class="link" href="">1997 Keys</a></td>
            </tr>
            <tr>
              <td>1996</td>
              <td><a class="link" href="">1996 Paper</a></td>
              <td><a class="link" href="">1996 Keys</a></td>
            </tr>
            <tr>
              <td>1995</td>
              <td><a class="link" href="">1995 Paper</a></td>
              <td><a class="link" href="">1995 Keys</a></td>
            </tr>
            <tr>
              <td>1994</td>
              <td><a class="link" href="">1994 Paper</a></td>
              <td><a class="link" href="">1994 Keys</a></td>
            </tr>
            <tr>
              <td>1993</td>
              <td><a class="link" href="">1993 Paper</a></td>
              <td><a class="link" href="">1993 Keys</a></td>
            </tr>
            <tr>
              <td>1992</td>
              <td><a class="link" href="">1992 Paper</a></td>
              <td><a class="link" href="">1992 Keys</a></td>
            </tr>
            <tr>
              <td>1991</td>
              <td><a class="link" href="">1991 Paper</a></td>
              <td><a class="link" href="">1991 Keys</a></td>
            </tr>
            
          </table>
        </div>
      </section>

</body>
</html>

src/templates/gate/books_notes/book/book.html
<!DOCTYPE html>
<html>
<head>
  <title>Gate books</title>
  <link rel="icon" type="image/ico" href="capture.png" />
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="books.css">
  <link rel="icon" type="image/ico" href="title.png" />
  <script src="https://kit.fontawesome.com/8a9412ad16.js"></script>
 <script>
function openNav() {
  document.getElementById("myNav").style.width = "100%";
}

function closeNav() {
  document.getElementById("myNav").style.width = "0%";
}
</script>
</head>
<body>
<section id="Nav">
   <div id="myNav" class="overlay">
  	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  	<div class="overlay-content">
    	<a href="../../index.html" onclick="closeNav()"></i>MainPage</a>
    	<a href="#"></i>Gate- books & notes</a>
    	<a href="#"></i>Gate- videos</a>
    	<a href="#"></i>Gate- Preparation<sup>online resource</sup></a>
    		<a href="https://chat.whatsapp.com/HM9VJz4a8Ce0TvUZingcxF" target="_blank" class="whataap" title="Join to our whataap group----->>">--need any book??</a>
    </div>
   </div>
   <div>
 <span style="font-size:30px;cursor:pointer" class="Menu" onclick="openNav()">&#9776;</span>
 <img class="logo" id="logo" src="image.jpg">
</div>
			</section>
			<section id="navbar">
				<div class="topnav">
  <a class="active" href="#">BOOK SUGGESTION</a>
  <a href="../notes/notes.html">NOTES</a>
   <a href="../Pre/previous.html" >QUESTION PAPER<h6 style="margin-top:-5px;text-align: right;font-size: 10px; margin-bottom:-6px;">Previous year</h6></a>
  <a href="../motivation/motivation.html">MOTIVATION</a>
</div>
			</section>

      <section id="table">
        <img class="img" src="img.png">
        <h3>List of Best Books for GATE CSE 2020 [Suggested by GATE Toppers!]</h3>
        <div class="table">
          <table>
            <tr class="sub">
              <td>Subject</td>
              <td>Book Name</td>
              <td>Author Name</td>
              <td>Click here</td>
            </tr>
            <tr>
              <td>C programming</td>
              <td>The C Programming language</td>
              <td>Brain W.Kenighan, Dennis M.Ritchie, (Edition:2)</td>
               <td><a class="follow" href="https://www.google.com">Follow</a></td>
            </tr>
            <tr>
              <td>Data Structure</td>
              <td>Classsic Data Structure</td>
              <td>Debasis Samanta, (Edition:2)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Algorithms</td>
              <td>Introduction to Algorithms</td>
              <td>Thomas H.Cormen, Charles E.Leiserson, Ronald L. Rivest and Clifford Stein, (Edition)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Computer Networks</td>
              <td>Computer Networking:A Top-Down Approch</td>
              <td>James F.Kurose, Keith W.Rose, (Edition:6)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Operating System</td>
              <td>Opearting System Concepts</td>
              <td>Silberschatz, Galvin, Gagne, (Edition:8)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Database</td>
              <td>Database System Concepts</td>
              <td>Silberschatz. Sudarshan, Korth, (Edition:6)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Theory of computation</td>
              <td> An Introduction to Formal Language and Automata</td>
              <td>Peter Linz, (Edition:5)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Computer Organization & Architecture</td>
              <td>Computer Organization and Architecture</td>
              <td>Hamacher, Vranesic, Zaky, (Edition:7)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Digital Logic</td>
              <td>Digital Logic & Computer Design</td>
              <td>M. Morris Mnano, (Edition)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Compiler Design</td>
              <td>Compiler:Principle</td>
              <td>Alfred.Aho, Ravi Sethi, D.Jeffrey Ulman, (Edition:2)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Engineering Mathematics</td>
              <td>Higher Engineering Mathematics</td>
              <td>B.S. Grewal, (Edition:43)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Discrete Mathematics</td>
              <td>Discrete Mathematics and Its Application</td>
              <td>Kenneth Rosen</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Reasoning</td>
              <td>A Modern Approch to Verbal & Non-Verbal Reasoning</td>
              <td>R.S. Aggarawal, (Edition:Revised)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
            <tr>
              <td>Apitude</td>
              <td>Quantitive Aptitude For Competitive Examination</td>
              <td>R.S. Aggarawal, (Edition:7)</td>
               <td><a class="follow" href="">Follow</a></td>
            </tr>
          </table>
        </div>
      </section>
</body>
</html>

src/templates/gate/content.html
d{% extends 'gate/gate.html' %}

{% block content %}

<h3>Section 1: Engineering Mathematics</h3>
<h4>Discrete Mathematics:</h4> <h6>Propositional and first order logic. Sets, relations, functions, partial orders and lattices. Groups. Graphs: connectivity, matching, coloring. Combinatorics: counting, recurrence relations, generating functions.</h6>

<h4>Linear Algebra:</h4> <h6>Matrices, determinants, system of linear equations, eigenvalues and eigen vectors, LU decomposition.</h6>

<h4>Calculus:</h4> <h6>Limits, continuity and differentiability. Maxima and minima. Mean value theorem. Integration.</h6>

<h4>Probability:</h4> <h6>Random variables. Uniform, normal, exponential, poisson and binomial distributions. Mean, median, mode and standard deviation. Conditional probability and Bayes theorem.</h6>
<h3>Section 2: Digital Logic</h3><h6>
Boolean algebra. Combinational and sequential circuits. Minimization. Number representations and computer arithmetic (fixed and floating point).</h6>

<h3>Section 3: Computer Organization and Architecture</h3><h6>
Machine instructions and addressing modes. ALU, data‐path and control unit. Instruction pipelining. Memory hierarchy: cache, main memory and secondary storage; I/O interface (interrupt and DMA mode).</h6>

<h3>Section 4: Programming and Data Structures</h3><h6>
Programming in C. Recursion. Arrays, stacks, queues, linked lists, trees, binary search trees, binary heaps, graphs.</h6>

<h3>Section 5: Algorithms</h3><h6>
Searching, sorting, hashing. Asymptotic worst case time and space complexity. Algorithm design techniques: greedy, dynamic programming and divide‐and‐conquer. Graph search, minimum spanning trees, shortest paths.</h6>

<h3>Section 6: Theory of Computation</h3><h6>
Regular expressions and finite automata. Context-free grammars and push-down automata. Regular and contex-free languages, pumping lemma. Turing machines and undecidability.</h6>
<h3>Section 7: Compiler Design</h3><h6>
Lexical analysis, parsing, syntax-directed translation. Runtime environments. Intermediate code generation.</h6>

<h3>Section 8: Operating System</h3><h6>
Processes, threads, inter‐process communication, concurrency and synchronization. Deadlock. CPU scheduling. Memory management and virtual memory. File systems.</h6>

<h4 style=" font-weight: lighter;font-style: italic;color: rgba(44, 62, 80,1.0);margin-top: -35px;">GATE 2020 Syllabus for Computer Science and Information Technology Section 9</h4>

<h3>Section 9: Databases</h3><h6>
ER‐model. Relational model: relational algebra, tuple calculus, SQL. Integrity constraints, normal forms. File organization, indexing (e.g., B and B+ trees). Transactions and concurrency control.</h6>

<h4 style="font-style: italic; font-weight:lighter;color: rgba(44, 62, 80,1.0);margin-top: 0px;">GATE 2020 Syllabus for Computer Science and Information Technology Section 10</h4>

<h3>Section 10: Computer Networks</h3><h6>
Concept of layering. LAN technologies (Ethernet). Flow and error control techniques, switching. IPv4/IPv6, routers and routing algorithms (distance vector, link state). TCP/UDP and sockets, congestion control. Application layer protocols (DNS, SMTP, POP, FTP, HTTP). Basics of Wi-Fi. Network security: authentication, basics of public key and private key cryptography, digital signatures and certificates, firewalls.</h6>
      
      <h4 style="font-size: 18px; font-weight: lighter; font-style: italic;color: rgba(44, 62, 80,1.0);">Download GATE 2020 Syllabus for Computer Science and Information Technology (pdf)<a href="http://www.gate.iitg.ac.in/Syllabi/CS_Computer-Science-and-Information-Technology.pdf" style="color: rgba(52, 73, 94,1.0); text-decoration: none;
      margin-left:4px; font-weight: 500;font-family:cursive;"><i class="fas fa-download"></i>Download</a></h4>
      <br>


{% endblock %}

src/templates/gate/materials/books&notes.html
<!DOCTYPE html>
<html>
<head>
  <title>E-library</title>
  <link rel="icon" type="image/ico" href="capture.png" />
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="books.css">
  <script src="https://kit.fontawesome.com/8a9412ad16.js"></script>
 <script>
function openNav() {
  document.getElementById("myNav").style.width = "100%";
}

function closeNav() {
  document.getElementById("myNav").style.width = "0%";
}
</script>
</head>
<body>
<section id="Nav">
   <div id="myNav" class="overlay">
  	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  	<div class="overlay-content">
    	<a href="#logo" onclick="closeNav()"></i>MainPage</a>
    	<a href="#"></i>Gate- books & notes</a>
    	<a href="#"></i>Gate- videos</a>
    	<a href="#"></i>Gate- Preparation<sup>online resource</sup></a>
    		<a href="https://chat.whatsapp.com/HM9VJz4a8Ce0TvUZingcxF" target="_blank" class="whataap" title="Join to our whataap group----->>">--need any book??</a>
    </div>
   </div>
   <div>
 <span style="font-size:30px;cursor:pointer" class="Menu" onclick="openNav()">&#9776;</span>
 <img class="logo" id="logo" src="image.jpg">
</div>
			</section>
			<section id="navbar">
				<div class="topnav">
  <a class="active" href="#home">Home</a>
  <a href="#news">News</a>
  <a href="#contact">Contact</a>
  <a href="#about">About</a>
</div>
			</section>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block content %} 

<div class="row">
	<div class="column">
  		<div class="card">
  			<a href ="request"><img src="https://www.goodfreephotos.com/albums/vector-images/red-books-vector-art.png" alt="Books" style="width:100%"></a>
  			<h4><b><strong>Gate</strong></b></h4>
		</div>
	</div>

	<div class="column">
  		<div class="card">
  			<a href =><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Gnome-application-certificate.svg/1024px-Gnome-application-certificate.svg.png" alt="Certificate" style="width:100%"></a>
  			<h4><b><strong>Online Courses</strong></b></h4>
		</div>
	</div>
	
</div>
{% endblock %}

src/templates/request.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background-image: url('https://cdn.pixabay.com/photo/2019/08/09/06/08/library-4394441_960_720.jpg');
  background-size: cover;
  height: 100%;
  width: 100%;
}

.flip-card {
  background-color: transparent;
  width: 300px;
  height: 300px;
  perspective: 1000px;
}

.flip-card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  text-align: center;
  transition: transform 0.6s;
  transform-style: preserve-3d;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
}

.flip-card:hover .flip-card-inner {
  transform: rotateY(180deg);
}

.flip-card-front, .flip-card-back {
  position: absolute;
  width: 100%;
  height: 100%;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
}

.flip-card-front {
  background-color: #bbb;
  color: black;
}

.flip-card-back {
  background-color: #2980b9;
  color: white;
  transform: rotateY(180deg);
}
</style>
</head>
<body>
<center>
<h1>Card Flip with Text</h1>
<h3>Hover over the image below:</h3>

<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="img_avatar.png" alt="Avatar" style="width:300px;height:300px;">
    </div>
    <div class="flip-card-back">
		<div style="text-align:auto">
  			<form method="post" action="/gate/">{% csrf_token %}

  				<center>
  				{{ form.as_table }}</center>
   				<!--<tr><th>Choose your stream:-</th><td><ul id="id_Subject">
    <tc><label for="id_Subject_0"><input type="radio" name="Subject" value="cs" required id="id_Subject_0">
 CSE/IT</label>

</tc>
    <tc><label for="id_Subject_1"><input type="radio" name="Subject" value="me" required id="id_Subject_1">
 ME</label>

</tc>
    <tc><label for="id_Subject_2"><input type="radio" name="Subject" value="ece" required id="id_Subject_2">
 ECE</label>

</tc>
    <tc><label for="id_Subject_3"><input type="radio" name="Subject" value="ee" required id="id_Subject_3">
 EE</label>

</tc>
</ul></td></tr> -->
    		<button type="submit">Send</button>
  			</form></div>
    	</div>
  	</div>
	</div>
</center>
</body>
</html>